<?php
/**
 *   @author     danrcoull <ttechitsolutions@gmail.com>
 *   @copyright  27/01/2020, 19:29 danrcoull
 *   @version   1.0.0
 *
 */

/**
 * @var $block \CoullWorks\BannerSlider\Block\Widget\BannerSlider
 * @var \Magento\Framework\Escaper $escaper
 */
$slider = $block->getSlider();

?>
<?php if($slider): ?>
    <?php if($slider->getEnabled()) : ?>
        <div class="slider <?= $escaper->escapeHtmlAttr($block->getClass()); ?>">

            <?php $slides = $block->getSliderSlides($slider); ?>
            <?php if($slides != false) : ?>

                <?php foreach ($slides as $slide) : ?>
                <?php
                /**
                 * @var $slide \CoullWorks\BannerSlider\Api\Data\BannersInterface
                 */
                $slide = $block->getSlide($slide) ; ?>


                <div class="slide">
                    <?php if($slide->getBannerLink()) :?>
                    <a href="<?= $escaper->escapeUrl($slide->getBannerLink());?>" title="<?= $escaper->escapeHtmlAttr($slide->getBannerName()); ?>">
                        <?php endif; ?>
                        <picture class="<?= $escaper->escapeHtmlAttr($block->getImageClass()); ?>">
                            <source media="(min-width: 650px)" srcset="<?= $escaper->escapeUrl($slide->getImageUrl('banner_image')); ?>">
                            <source media="(min-width: 465px)" srcset="<?= $escaper->escapeUrl($slide->getImageUrl('banner_image_mobile')); ?>">
                            <img loading="lazy" src="<?= $escaper->escapeUrl($slide->getImageUrl('banner_image_mobile')); ?>" alt="<?= $escaper->escapeHtmlAttr($slide->getBannerName()); ?>" style="width:auto;">
                        </picture>

                        <?php if($slide->getShowBannerOverlay()) : ?>
                            <div class="overlay">
                                <div class="inner">
                                    <?= /* @noEscape */ $block->processContent($slide->getBannerOverlayContent()); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if($slide->getBannerLink()) :?>
                    </a>
                <?php endif; ?>
                </div>
            <?php endforeach; ?>

                <script type="text/x-magento-init">
                {
                   ".slider": {
                      "slider": <?= /* @noEscape */ $block->getSliderConfig(); ?>
                   }
                }
                </script>
            <?php endif; ?>
        </div>
        <?php if($block->showTabs()) : ?>
            <div class="tabs full-width">
                <?php foreach ($slides as $slide) : ?>

                    <?php
                    /**
                     * @var $slide \CoullWorks\BannerSlider\Api\Data\BannersInterface
                     */
                    $slide = $block->getSlide($slide) ; ?>
                    <div class="tab">
                        <h4><?= $escaper->escapeHtml($slide->getBannerName());?></h4>
                    </div>
                <?php endforeach; ?>
            </div>
            <script type="text/x-magento-init">
                {
                   ".tabs": {
                       "slider": <?= /* @noEscape */ $block->getTabsConfig(); ?>
                   }
                }
                </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
